#!/bin/bash -e

set -eux

cd /app

ls -la

eval $(poetry env activate)
export DJANGO_MODE=prod
export STATIC_ROOT=/static

./manage.py migrate
./manage.py collectstatic --noinput --clear



exec "$@"
