# Generated by Django 5.1.5 on 2025-01-30 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayer_room_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayerpraiserequest',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
