# Generated by Django 5.1.5 on 2025-02-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayer_room_api', '0004_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayerpraiserequest',
            name='name',
            field=models.TextField(),
        ),
    ]
