# Generated by Django 5.1.5 on 2025-02-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayer_room_api', '0005_alter_prayerpraiserequest_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayerpraiserequest',
            name='name',
            field=models.TextField(default='Anon'),
        ),
    ]
