# Generated by Django 5.1.5 on 2025-03-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayer_room_api', '0006_alter_prayerpraiserequest_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayerpraiserequest',
            name='response_comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
