# Generated by Django 5.1.6 on 2025-09-02 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prayer_room_api", "0008_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="BannedWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.TextField()),
                (
                    "auto_action",
                    models.CharField(
                        choices=[
                            ("flag", "Flag Request"),
                            ("archive", "Archive Request"),
                        ],
                        default="flag",
                        max_length=255,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
