# Generated by Django 5.1.6 on 2025-12-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prayer_room_api", "0009_bannedword"),
    ]

    operations = [
        migrations.AddField(
            model_name="prayerpraiserequest",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
