# Generated by Django 5.1.6 on 2025-06-19 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prayer_room_api', '0009_prayerpraiserequest_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='enable_repsonse_notifications',
            new_name='enable_response_notifications',
        ),
    ]
