# Generated by Django 5.1.6 on 2025-12-02 14:44

from django.db import migrations
from django.db.models import F


def approve_existing_migrations(apps, schema_editor):
    PrayerPraiseRequest = apps.get_model("prayer_room_api", "PrayerPraiseRequest")

    PrayerPraiseRequest.objects.filter(
        archived_at__isnull=True, flagged_at__isnull=True
    ).update(approved_at=F("created_at"))


class Migration(migrations.Migration):

    dependencies = [
        ("prayer_room_api", "0010_prayerpraiserequest_approved_at"),
    ]

    operations = [
        migrations.RunPython(approve_existing_migrations, migrations.RunPython.noop)
    ]
