# Generated by Django 5.1.6 on 2025-12-02 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prayer_room_api", "0011_existing_approved_prayers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bannedword",
            name="auto_action",
            field=models.CharField(
                choices=[
                    ("flag", "Flag Request"),
                    ("archive", "Archive Request"),
                    ("approve", "Approve Request"),
                ],
                default="flag",
                max_length=255,
            ),
        ),
    ]
