# Generated by Django 5.1.6 on 2025-12-05 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prayer_room_api", "0012_alter_bannedword_auto_action"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="enable_repsonse_notifications",
            new_name="enable_response_notifications",
        ),
        migrations.AddField(
            model_name="prayerpraiserequest",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
