# Generated by Django 5.1.6 on 2025-12-05 12:17

from django.db import migrations


def seed_email_templates(apps, schema_editor):
    EmailTemplate = apps.get_model("prayer_room_api", "EmailTemplate")

    templates = [
        {
            "template_type": "moderator_digest",
            "subject": "Prayer Room: {{ pending_count }} pending, {{ flagged_count }} flagged",
            "body_markdown": """# Moderation Digest

Hi {{ recipient_name }},

Here's your hourly update from the Prayer Room:

## Pending Requests ({{ pending_count }})

{% if pending_requests %}
{% for request in pending_requests %}
- **{{ request.name }}**: {{ request.content|truncatewords:20 }}
{% endfor %}
{% else %}
No pending requests at this time.
{% endif %}

## Flagged Requests ({{ flagged_count }})

{% if flagged_requests %}
{% for request in flagged_requests %}
- **{{ request.name }}**: {{ request.content|truncatewords:20 }}
{% endfor %}
{% else %}
No flagged requests at this time.
{% endif %}

---

[View Moderation Dashboard]({{ moderation_url }})

*This is an automated message from the Prayer Room.*
""",
        },
        {
            "template_type": "user_digest",
            "subject": "Updates on your prayer requests",
            "body_markdown": """# Your Prayer Request Updates

Hi {{ recipient_name }},

Here's your {{ frequency }} update on your prayer requests:

## Responses to Your Requests

{% if requests_with_responses %}
{% for request in requests_with_responses %}
### Your request:
> {{ request.content|truncatewords:30 }}

**Response:** {{ request.response_comment }}

---
{% endfor %}
{% else %}
No new responses since your last digest.
{% endif %}

*Thank you for being part of our prayer community.*
""",
        },
        {
            "template_type": "response_notification",
            "subject": "Someone responded to your prayer request",
            "body_markdown": """# You've Received a Response

Hi {{ recipient_name }},

Someone has responded to your prayer request.

## Your Request:
> {{ request_content }}

## Response:
{{ response_text }}

---

*Thank you for sharing your prayer request with us.*
""",
        },
    ]

    for data in templates:
        EmailTemplate.objects.get_or_create(
            template_type=data["template_type"],
            defaults={
                "subject": data["subject"],
                "body_markdown": data["body_markdown"],
                "is_active": True,
            },
        )


def reverse_seed(apps, schema_editor):
    EmailTemplate = apps.get_model("prayer_room_api", "EmailTemplate")
    EmailTemplate.objects.filter(
        template_type__in=["moderator_digest", "user_digest", "response_notification"]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("prayer_room_api", "0014_email_templates"),
    ]

    operations = [
        migrations.RunPython(seed_email_templates, reverse_seed),
    ]
