# Generated by Django 5.1.6 on 2025-12-17 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prayer_room_api", "0016_create_celery_beat_schedules"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
