# Generated by Django 5.1.6 on 2026-02-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prayer_room_api", "0017_location_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrayerResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("link", "Link"),
                            ("video", "Video"),
                            ("audio", "Audio"),
                            ("text", "Text"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="URL for link, YouTube video, or audio resource",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Body text for text-type resources",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers appear first"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["sort_order", "-created_at"],
            },
        ),
    ]
