# Generated by Django 5.1.6 on 2026-02-21 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prayer_room_api", "0018_prayerresource"),
    ]

    operations = [
        migrations.AddField(
            model_name="prayerresource",
            name="section",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"resource_type": "section"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="prayer_room_api.prayerresource",
            ),
        ),
        migrations.AlterField(
            model_name="prayerresource",
            name="resource_type",
            field=models.CharField(
                choices=[
                    ("section", "Section"),
                    ("link", "Link"),
                    ("video", "Video"),
                    ("audio", "Audio"),
                    ("text", "Text"),
                ],
                max_length=20,
            ),
        ),
    ]
