# Generated by Django 5.1.6 on 2026-05-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayer_room_api', '0019_prayerresource_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayerpraiserequest',
            name='response_skipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
